version: '2'

services:

#  mongo:
#    image: mongo:latest
#    container_name: "mongodb"
#    environment:
#      - MONGO_LOG_DIR=/dev/
#    volumes:
#      - ./data/db:/data/db
#      - ./mongo_realdata:/tmp/mongodata
#    ports:
#       - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null 
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "20m"
#        max-file: "1"

#  api-rest:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#      #image: marianodim/api-rest
#    container_name: "api-rest"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo

  mongo-express:
    image: autopilotpattern/mongo-express
    restart: always
    mem_limit: "512m"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
    labels:
      - triton.cns.services=mongo-express
    ports:
      - "8081:8081"

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
