apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: api-rest
  name: api-rest-ml
spec:
  replicas: 6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api-rest-ml
    spec:
      containers:
      - image: marianodim/api-rest-ml
        name: api-rest-ml
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
